#! /bin/sh

case "$1" in
  start)
    echo "Module load"
    start-stop-daemon -S -n init -a /ldd/scull_load
    start-stop-daemon -S -n init -a /ldd/module_load -- faulty
    start-stop-daemon -S -n init -a /ldd/module_load -- hello
    ;;
  stop)
    echo "Module remove"
    start-stop-daemon -K -n scull_load
    start-stop-daemon -K -n module_load
    start-stop-daemon -S -n init -a /ldd/scull_unload
    start-stop-daemon -S -n init -a /ldd/module_unload -- faulty
    start-stop-daemon -S -n init -a /ldd/module_unload -- hello
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
